Controllers/BlogsController.cs
using Foodly_new.Data;
using Foodly_new.Models.DomainModels;
using Foodly_new.Models.EfModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PagedList.Core;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Foodly_new.Controllers
{
    public class BlogsController : Controller
    {
        private readonly UserManager<UserIdentity> _userManager;
        EFContext c = new EFContext();

        public BlogsController(UserManager<UserIdentity> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index(int page = 1,int pageSize=6)
        {
            PagedList<Review> model = new PagedList<Review>(c.Reviews.Where(x=>x.Publish==true&&x.IsDeleted==false).OrderByDescending(x => x.PublishDate), page, pageSize);
            return View("Index", model);
        }
        public async Task<IActionResult> Blog(string id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                try
                {
                    var blogContext = c.Reviews.Find(id);
                    var se = await _userManager.FindByIdAsync(blogContext.UserID);
                    ViewData["blogContent"] = blogContext.Blog.ToString();
                    ViewData["BlogHeader"] = blogContext.Header;
                    ViewData["BlogPictureURL"] = blogContext.BannerImage;
                    ViewData["BlogPrice"] = blogContext.Price;
                    ViewData["BlogPublishDate"] = blogContext.PublishDate;
                    ViewData["BlogRestaurantName"] = blogContext.RestaurantName;
                    ViewData["BlogStar"] = blogContext.Star;
                    ViewData["BlogUser"] = se.UserName;
                    ViewData["PhotoProfile"] = se.Profilephoto;
                    ViewData["ShorCast"] = blogContext.ShortCast;
                    ViewData["id"] = blogContext.ReviewID;
                    ViewData["UserId"] = blogContext.UserID;

                    var commentcontext = c.Comments.Where(x=>x.ReviewID==blogContext.ReviewID).ToList();

                    return View(commentcontext);
                }
                catch
                {
                    return RedirectToAction(nameof(Index));
                }
            }
        }

        [HttpPost]
        public IActionResult Blog(string ReviewID, string Header)
        {
            try
            {
                if (Header == "Delete")
                {
                    if (ReviewID != null)
                    {
                        List<Review> r = new List<Review>();
                        r = c.Reviews.Where(x => x.ReviewID == ReviewID && x.IsDeleted == false).ToList<Review>();
                        foreach (var item in r)
                        {
                            item.Publish = false;
                            item.IsDeleted = true;
                            c.Update(item);
                            c.SaveChanges();
                        }
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ViewData["Error"] = "Bir hata oluştu #3303";
                        return View();
                    }
                }
                else
                {
                    ViewData["Error"] = "Bir hata oluştu #3304";
                    return View();
                }
            }
            catch
            {
                ViewData["Error"] = "Bir hata oluştu #3305";
                return View();
            }

        }

        [HttpGet]
        [Authorize]
        public IActionResult WriteBlog()
        {
            return View();
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult WriteBlog(string Header, string ShortCast, string restaurantName, string star, int price, string Blog)
        {
            try
            {
            Review blog = new Review();
            //image to BYTE
            foreach (var file in Request.Form.Files)
            {
                MemoryStream ms = new MemoryStream();
                file.CopyTo(ms);
                var imageData = ms.ToArray();

                ms.Close();
                ms.Dispose();
                string imageBase64Data = Convert.ToBase64String(imageData);
                blog.BannerImage = string.Format("data:image/jpg;base64,{0}", imageBase64Data);
                break;
            }
            //DATABASE ADD
            blog.ReviewID = Guid.NewGuid().ToString();
            blog.ShortCast = ShortCast;
            blog.Header = Header;
            blog.Price = price;
            blog.Star = Convert.ToDouble(star);
            blog.Blog = Blog;
            blog.Publish = false;
            blog.IsDeleted = false;
            blog.RestaurantName = restaurantName;
            blog.PublishDate = DateTime.Now;
            blog.UserID = _userManager.GetUserId(User);
            c.Reviews.Add(blog);
            c.SaveChanges();

            return View();
            }
             catch 
            {
                ViewData["Error"] = "Bir şeyler Ters gitti";
                return View();
            }
        }

        public async Task<IActionResult> AddComment(string id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                try
                {
                    var blogContext = c.Reviews.Find(id);
                    var se = await _userManager.FindByIdAsync(blogContext.UserID);
                    ViewData["BlogHeader"] = blogContext.Header;
                    ViewData["BlogPictureURL"] = blogContext.BannerImage;
                    ViewData["BlogPublishDate"] = blogContext.PublishDate;
                    ViewData["PhotoProfile"] = se.Profilephoto;
                    ViewData["ShortCast"] = blogContext.ShortCast;
                    ViewData["id"] = blogContext.ReviewID;
                    ViewData["BlogUser"] = se.UserName;
                    return View();
                }
                catch
                {
                    return RedirectToAction(nameof(Index));
                }
            }
        }
        [HttpPost]
        [Authorize]
        public IActionResult AddComment(string ReviewID,string Entry)
        {
            var comments = c.Comments.Add(new Comment
            {
                ReviewID = ReviewID,
                Entry = Entry,
                CommentID = Guid.NewGuid().ToString(),
                PublishDate = DateTime.Now,
                UserID = _userManager.GetUserId(User)
            }) ;
            var s = c.SaveChanges();
            if (s > 0)
            {
                return RedirectToPage("/Blogs/Blog",ReviewID);
            }
            return View();
        }
    }
}

Controllers/UserController.cs
using Foodly_new.Data;
using Foodly_new.Models.DomainModels;
using Foodly_new.Models.EfModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PagedList.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Foodly_new.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<UserIdentity> _userManager;
        EFContext c = new EFContext();
        public UserController(UserManager<UserIdentity> userManager)
        {
            _userManager = userManager;           
        }
        public async Task<IActionResult> Index()
        {
           var user= await _userManager.GetUserAsync(User);
            return RedirectToPage("/profile/", user.Id);
        }
        [HttpGet]
        public async Task<IActionResult> Profile(string id, int page = 1, int pageSize = 6)
        {
            var user = await _userManager.FindByIdAsync(id);
            PagedList<Review> model = new PagedList<Review>(c.Reviews.Where(x => x.Publish == true && x.IsDeleted == false && x.UserID==id), page, pageSize);
            ViewData["Username"] = user.UserName;
            ViewData["profilephoto"] = user.Profilephoto;
            return View("profile", model);
        }
    }
}

Views/User/Profile.cshtml
@{
    ViewData["Title"] = "";
}
@inject UserManager<UserIdentity> UserManager
@addTagHelper *,PagedList.Core.Mvc
@model PagedList.Core.IPagedList<Review>


<section class="hero-wrap hero-wrap-2" style="background-image: url(/images/bg_2.jpg);" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate text-center mb-4">
                <h1 class="mb-2 bread">@ViewData["Username"] Adlı kullanıcının Profili</h1>
            </div>
        </div>
    </div>
</section>
@*Blogs lists and pages*@
<section class="ftco-section ftco-wrap-about">
    <div class="container">
        <div class="row">
            <div class="col-md-7 d-flex">
                <div class="img img-2 ml-md-2" style="background-image: url(@ViewData["profilephoto"]);"></div>
            </div>
            <div class="col-md-5 wrap-about pt-5 pt-md-5 pb-md-3 ftco-animate">
                <div class="heading-section mb-4 my-5 my-md-0">
                    <span class="subheading">@ViewData["Username"]</span><br><br>
                      <h2 class="mb-4">'in paylaştığı makaleler</h2>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section bg-light">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                var x = await UserManager.FindByIdAsync(item.UserID);
                ViewData["Username"] = x.UserName;
                <div class="col-md-4 ftco-animate">
                    <div class="blog-entry">
                        <a href="/Blogs/blog/@item.ReviewID" class="block-20" style="background-image: url(@item.BannerImage);"></a>
                        <div class="text pt-3 pb-4 px-4">
                            <div class="meta">
                                @{
                                    int starCount = Convert.ToInt16(item.Star);
                                    for (int i = 1; i <= starCount; i++)
                                    {
                                        <span class="golden fas fa-star"></span>
                                    }
                                    for (int i = starCount + 1; i <= 5; i++)
                                    {
                                        <span class="golden far fa-star"></span>
                                    }
                                }<br />
                                <div>@item.PublishDate</div>
                                <div>@ViewData["Username"]</div>
                            </div>
                            <h3 class="heading"><a href="/Blogs/blog/@item.ReviewID">@item.Header</a></h3>
                            <div>@item.ShortCast</div>
                            <p class="clearfix">
                                <a href="/Blogs/blog/@item.ReviewID" class="float-left read"><u>Makaleyi oku</u></a>
                            </p>
                        </div>
                    </div>
                    @{
                        ViewData["Title"] = ViewData["Username"];
                        ViewData["Header"] = ViewData["Username"] + " adlı kullanıcının makaleleri";                       
                    }
                </div>
            }
        </div>
        <div class="row no-gutters my-5">
            <div class="col text-center">
                @if (ViewData["Model"] != "Bu Kullanıcı henüz bir şey paylaşmamış")
                {
                    <pager list="@Model" asp-controller="Blogs" asp-action="Index" />
                }
            </div>
        </div>
    </div>

</section>